name: test
on: [push]
jobs:
  security:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@master
        - name: Run Snyk to check for vulnerabilities
          uses: snyk/actions/node@master
          env:
            SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
  setup:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
      - uses: actions/checkout@v3
      - run: make setup
      - run: make test
      - run: make lint
      