name: test
on: [push]
jobs:
  setup:
    runs-on: ${{ matrix.os }}
    stretegy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v3
      - run: make setup
  tests:
    needs: setup
    runs-on: ${{ matrix.os }}
    stretegy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    - run: make test
  lint:
    runs-on: ${{ matrix.os }}
    stretegy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    - uses: actions/checkout@v3
    - run: make lint